pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "AbrovaTraceExample"
include ':app'
include ':abrova-trace-sdk'
project(':abrova-trace-sdk').projectDir = new File(settingsDir, '../abrova-trace-sdk')
